### ISSUE TITLE
"Play now" button easy to press accidentally

### ISSUE THREAD

**Issue by elsander** [jacarval/karaoke-tube#2]
Right now, seems like the play now button will stop whatever song is currently playing and play the song you're looking at. It's easy to press accidentally, and it would probably be preferable to have it queue the song next, rather than stop the current song in the middle.

**Comment by jacarval** [comment]
working on this now. i think it might be preferable to have one 'kiosk' that can control playing songs immediately and changing the playlist and other clients that can add songs but only view the current playlist
